version: '3.8'

services:
  # Elasticsearch para tenant_id = t0
  elasticsearch_tenant0:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data_0:/usr/share/elasticsearch/data

  # Elasticsearch para tenant_id = t1
  elasticsearch_tenant1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ports:
      - "9201:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data_1:/usr/share/elasticsearch/data

volumes:
  es_data_0:
  es_data_1: