org: ${env:ORG_NAME}
service: api-bebes

provider:
  name: aws
  region: us-east-1
  runtime: python3.13
  timeout: 30
  iam:
    role: arn:aws:iam::910414521227:role/LabRole
  environment:
    TABLE_USUARIOS: t_usuarios2
    TABLE_TOKENS: t_tokens_acceso1
    TABLE_PRODUCTOS: t_productos1
    TABLE_COMPRAS: t_compras1

functions:

  loginUsuario:
    handler: api-usuario/LoginUsuario.lambda_handler
    events:
      - http:
          path: /usuario/login
          method: post
          cors: true

  registrarUsuario:
    handler: api-usuario/RegistroUsuario.lambda_handler
    events:
      - http:
          path: /usuario/signup
          method: post
          cors: true
  validarUsuario:
    handler: api-usuario/ValidarTokenUsuario.lambda_handler
    events:
      - http:
          path: /usuario/validar
          method: post
          cors: true

  listarProducto:
    handler: api-producto/ListarProducto.handler
    runtime: nodejs20.x
    package:
      include:
        - api-producto/ListarProducto.js
        - api-producto/package.json
        - api-producto/node_modules/**
    events:
      - http:
          path: /producto/listar
          method: post
          cors: true

  crearProducto:
    handler: api-producto/CrearProducto.handler
    runtime: nodejs20.x
    package:
      include:
        - api-producto/CrearProducto.js
        - api-producto/package.json
        - api-producto/node_modules/**
    events:
      - http:
          path: /producto/crear
          method: post
          cors: true

  buscarProducto:
    handler: api-producto/BuscarProducto.handler
    runtime: nodejs20.x
    package:
      include:
        - api-producto/BuscarProducto.js
        - api-producto/package.json
        - api-producto/node_modules/**
    events:
      - http:
          path: /producto/buscar
          method: post
          cors: true

  modificarProducto:
    handler: api-producto/ModificarProducto.handler
    runtime: nodejs20.x
    package:
      include:
        - api-producto/ModificarProducto.js
        - api-producto/package.json
        - api-producto/node_modules/**
    events:
      - http:
          path: /producto/modificar
          method: put
          cors: true

  eliminarProducto:
    handler: api-producto/EliminarProducto.handler
    runtime: nodejs20.x
    package:
      include:
        - api-producto/EliminarProducto.js
        - api-producto/package.json
        - api-producto/node_modules/**
    events:
      - http:
          path: /producto/eliminar
          method: delete
          cors: true

  registrarCompra:
    handler: api-compra/RegistrarCompra.lambda_handler
    events:
      - http:
          path: /compra/registrar
          method: post
          cors: true

  listarCompras:
    handler: api-compra/ListarCompra.lambda_handler
    events:
      - http:
          path: /compra/listar
          method: post
          cors: true

  # === INDEXACIÓN POR STREAM ===
  indexarProducto:
    handler: IndexarProducto.lambda_handler
    package:
      include:
        - IndexarProducto.py
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - TablaProductos
              - StreamArn
          batchSize: 1
          startingPosition: LATEST

  indexarCompra:
    handler: IndexarCompra.lambda_handler
    package:
      include:
        - IndexarCompra.py
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - TablaCompras
              - StreamArn
          batchSize: 1
          startingPosition: LATEST

resources:
  Resources:

    TablaUsuarios2:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_usuarios2
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE

    TablaTokens:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_tokens_acceso1
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH

    TablaProductos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_productos1
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: producto_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: producto_id
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    TablaCompras:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_compras1
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: compra_id
            AttributeType: S
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: compra_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: idx_usuario
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: user_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL 
        StreamSpecification:
          StreamViewType: NEW_IMAGE